Food.Web/Models/ErrorViewModel.cs
namespace Food.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Food.Web/Models/HomeViewModel.cs
using Food.Data.Models;

namespace Food.Web.Models
{
    public class HomeViewModel
    {
        public string? Name { get; set; }
        public IEnumerable<Restaurant> data { get; set; }
    }
}

Food.Web/Controllers/HomeController.cs
using Food.Data.Services;
using Food.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Food.Web.Controllers
{
    public class HomeController : Controller
    {

        IRestaurantData db;
        public HomeController(IRestaurantData db)
        {
            this.db = db;
        }

        public IActionResult Index(string name)
        {
            var model = db.GetAll();

            return View(model);
        }

        public IActionResult Privacy()
        {
            var model = db.GetAll();
            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Food.Web/Controllers/RestaurantsController.cs
using Food.Data.Models;
using Food.Data.Services;
using Microsoft.AspNetCore.Mvc;

namespace Food.Web.Controllers
{
    public class RestaurantsController : Controller
    {
        public readonly IRestaurantData db;
        public RestaurantsController(IRestaurantData db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            var model = db.GetAll();
            return View(model);
        }
        public IActionResult Details(int id)
        {

            var model = db.Get(id);
            if (model == null)
            {

                return View("NotFound");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.Add(restaurant);

                return RedirectToAction("Details", new { id = restaurant.Id });
            }
            return View();

        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = db.Get(id);
            if (model == null)
            {
                return View("NotFound");
            }
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.Update(restaurant);
                return RedirectToAction("Details", new { id = restaurant.Id });
            }
            return View(restaurant);

        }
    }
}

Food.Web/Views/Home/Index.cshtml
@model IEnumerable<Food.Data.Models.Restaurant>
@*@model food.web.models.homeviewmodel*@

@{
    // ViewData["Title"] = "Home Page";
    ViewBag.Title = "Home";
}

<div >
    @*<h1 class="display-4">@DateTime.Now.Year</h1>*@
    <h1>We have @Model.Count() restaurants.</h1>
   @* <ul>
        @foreach (var r in Model)
        {
            <li>@r.Name</li>
        }
    </ul>*@
</div>

Food.Web/Views/Restaurants/Create.cshtml
@using Food.Data.Models
@model Food.Data.Models.Restaurant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuisine" class="control-label"></label>

                @Html.DropDownListFor(model => model.Cuisine,
                (from CuisineType e in Enum.GetValues(typeof(CuisineType))
                select new SelectListItem { Value = e.ToString(), Text = e.ToString() }),
                "--Select--", new { @class = "form-control" })

                <span asp-validation-for="Cuisine" class="text-danger"></span>
                <br />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Food.Web/Views/Restaurants/Details.cshtml
@model Food.Data.Models.Restaurant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cuisine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cuisine)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Food.Web/Views/Restaurants/Edit.cshtml
@using Food.Data.Models
@model Food.Data.Models.Restaurant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuisine" class="control-label"></label>
                @Html.DropDownListFor(model => model.Cuisine,
                (from CuisineType e in Enum.GetValues(typeof(CuisineType))
                select new SelectListItem { Value = e.ToString(), Text = e.ToString() }),
                "--Select--", new { @class = "form-control" })
                <span asp-validation-for="Cuisine" class="text-danger"></span>
                <br/>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Food.Web/Views/Restaurants/Index.cshtml
@model IEnumerable<Food.Data.Models.Restaurant>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cuisine)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cuisine)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.Id  }) |
                @Html.ActionLink("Details", "Details", new {  id=item.Id  }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id  })
            </td>
        </tr>
}
    </tbody>
</table>

Food.Web/Views/Restaurants/NotFound.cshtml
@*
   
*@

@{
    ViewBag.Title="NotFound";
}
<h3>Sorry, We couldn't find this restaurant.</h3>

@Html.ActionLink("Back To Restaurants List","Index")

Food.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Food.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Food.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Food.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="Index">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Food.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>